### ISSUE TITLE
已star，分辨率设置为2k，lol内客户端才有1920的选项，分辨率切回1920后，客户端分辨率也变小了。请问楼主怎么整出来的

### ISSUE THREAD

**Issue by XNNNN** [frei-x/LOL-Yun-Ding-Zhi-Yi#5]

**Comment by frei-x** [comment]
还要看操作系统的缩放。 例如分辨率是1920x1080，缩放比是100％， 那么显示分辨率就是1920x1080。如果缩放比是125％，那么实际显示分辨率响应缩小25％------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;X_NNNNN&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月25日(星期六) 晚上6:55
收件人:&nbsp;&quot;frei-x/LOL-Yun-Ding-Zhi-Yi&quot;<LOL-Yun-Ding-Zhi-Yi@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[frei-x/LOL-Yun-Ding-Zhi-Yi] 已star，分辨率设置为2k，lol内客户端才有1920的选项，分辨率切回1920后，客户端分辨率也变小了。请问楼主怎么整出来的 (#5)

**Comment by XNNNN** [comment]
好的谢谢。
